### ISSUE TITLE
[adminPanel] Gestion des ressources champ description

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/laclasse-client#1]
Le champ description des ressources est difficilement modifiable, il est possible d'écrire, mais les espaces et retour à la ligne ne sont pas pris en compte.

**Comment by dlacroix** [comment]
Oups. Petit bug dans ERATS qui date de 8 jours suite à la mise en place de l'autoClose "stylisable". C'est corrigé.
