### ISSUE TITLE
[actu]

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/laclasse-client#12]
Description
les derniers posts de blogs de s'affichent pas dans le volet gauche

### Reproduction
[Sur quel environement l'anomalie est-elle intervenue ?] : firefox; compte sroche2 (admin à Mistral et personnel à Dargent 
la personne est abonnée à 2 blogs dont les posts sont inférieurs à 3 mois
[Comment le développeur peut-il le reproduire ? (Quel écran ? Quelles actions / boutons ? etc.)] : écran portail : 
Comportement attendu
[En quoi le comportement actuel n'est il pas correct ?] les post des blogs auxquels la personne est abonné (tuile blogs) ne s'affichent pas dans la volet gauche alors qu'ils datent de moins de 3mois. 
[Quel est le comportement attendu ?] les post devraient s'afficher automatiquement

### Aide au développeur
[Vous pouvez insérer ici des captures d'écrans pour aider le développeur à retrouver les informations]
[Vous pouvez aussi y inclure les fichiers qui posent problème dans le cas d'import de fichier par exemple]
[Si vous avez d'autres documents / informations à fournir, vous pouvez aussi les inclure ici]
[Pistes de réflexion sur la résolution de l'anomalie]
(anomalie peut etre due à un mot de passe dans le blog ou configuration spéciale?? )
![screenshot_2018-07-31 https www laclasse com 79](https://user-images.githubusercontent.com/24314392/43464752-2922de70-94dc-11e8-8627-fa831e952ce7.png)

**Comment by n-goncalves** [comment]
Je renote ici le résumé de la discussion avec Charlotte pour en garder une trace:

Cet utilisateur n'a pas de compte sur la plateforme blog de Wordpress, il n'est donc pas abonné à un blog d'où l'affichage vide sur le volet de gauche. 
Il y a pour l'instant 3 manières de créer des utilisateurs Wordpress,
* L'utilisateur clique sur la ressource Blog et l'utilisateur est créé et associé aux blogs le concernant. 
* L’utilisateur va sur le le lien d'authentification d'un blog de la plateforme, (example: http://ent-laclasse.blogs.laclasse.com/wp-login.php )
* Un gestionnaire de blog à la possibilité de créer des utilisateurs Wordpress via l'interface d'ajout ou d'édition des blogs afin de pouvoir les abonner même si ceux-ci n'ont pas encore de compte Wordpress. 

A réfléchir sur une différente façon de faire afin d'avoir un maximum d'utilisateur avec des news.

**Comment by n-goncalves** [comment]
Corrigé et passé en prod, à tester.
