### ISSUE TITLE
[Admin-Panel] Problème avec le tri initial dans "Fichiers d'alimentation"

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/laclasse-client#14]
Actuellement le tri est sur la date avec la plus récente en premier.  Mais lors du chargement initial, cela ne correspond pas à ce qui est affiché. A corriger donc pour rendre cet ordre fonctionnel.

Je me demande aussi s'il ne serait pas judicieux de mettre en place la pagination. En effet, avec un smartphone, cette liste peut être trop longue..

**Comment by n-goncalves** [comment]
Corrigé et déployé.
