### ISSUE TITLE
[OnlyOffice] Message d'erreur "right needed"

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/laclasse-client#19]
**Quel est l'application concernée ?**
Only Office dans les Docs 

**Quel est le problème ou la fonctionnalité non existante ?**
Si l'utilisateur n'a pas les droits, le message d'erreur est assez brut et en anglais
![right needed](https://user-images.githubusercontent.com/24314392/58172978-5b4b9a80-7c9a-11e9-881d-335468486f0c.PNG)

test réalisé sur l'environnement de production avec le compte de test sbillal, pour le document collaboratif suivant : https://www.laclasse.com/api/docs/400489/onlyoffice 

**Quelle solution serait à proposer ?**
Afficher un message d'erreur plus explicite : "Vous n'avez pas les droits pour accéder ou lire ce fichier collaboratif. Contactez la personne en charge de ce fichier pour obtenir les droits."

**Quelles alternatives peuvent être prises en compte**
--

**Contexte additionnel**
*La demande des utilisateurs est-elle forte ?* non
*La solution semble-t-elle facile à mettre en œuvre ?* oui ?
*La solution génère-t-elle des impacts autres ?* non

**Comment by dlacroix** [comment]
Corrigé sur la dev. En prod à la prochaine mise à jour
